FROM node:20-alpine

WORKDIR /app

# Copy dependency list
COPY package*.json ./

# Install dependency (allow legacy peer deps)
RUN npm install --legacy-peer-deps

# Copy semua source code
COPY . .

# Expose port 3000 (Next.js dev default)
EXPOSE 3000

CMD ["npm", "run", "dev"]
