###
POST http://localhost/v1/login
Content-Type: application/json

{
 "email": "erlanggahandika73@gmail.com",
  "password": "12345678"
}

###
GET http://localhost:3001/v1/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImp0aSI6Ijc5ZWU0NTczLWQ4ZGMtNDc0YS1hYWMxLTFkZmEyMDJkNjUyYiIsImlhdCI6MTc1OTc0NzAwNSwiZXhwIjoxNzYwMzUxODA1fQ.6VCYKN5288E2qm5lEvXx7WatgV8IlS0U9mnZhNpd75A

###
GET http://localhost/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InNhaHJvbmkgbG9wZSBidW5hIHRlZGR5IiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTk2NTk1NCwiZXhwIjoxNzU5OTY2ODU0fQ.KRUqRrfMpg7CVR56oQkV5kHSXSzvzxoclPpKPjYGKsE

###
POST http://localhost:3001/v1/token-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTY2NzQyNywiZXhwIjoxNzU5NjY4MzI3fQ.vYGZuUbzNF9pdLtAunhybTzGv_VRvW9w0VGVgMa6s7s
Content-Type: application/json

{
    "token_notification": "exposddf"
}

###
GET http://localhost:3001/v1/status-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTY2OTYzMywiZXhwIjoxNzU5NjcwNTMzfQ.7R7VnTEahHoSH0r19EMHKAP-WgQfp1druhijnfK9O3g

###
GET http://localhost/v1/list-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InNhaHJvbmkgbG9wZSBidW5hIHRlZGR5IiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTk3NjE4NSwiZXhwIjoxNzU5OTc3MDg1fQ.1o6i5zcI_Z5MOx-7Bvtzx21Pv8z-mF83idILSdLJpxw

###
GET http://localhost:3001/v1/list-notification-byid/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTcxOTc4NSwiZXhwIjoxNzU5NzIwNjg1fQ.gJgjtKSjM5daFLAARH4tiwbxeGAskRbwly9VofJsXT0

###
PATCH http://localhost:3001/v1/update-status-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTcxOTc4NSwiZXhwIjoxNzU5NzIwNjg1fQ.gJgjtKSjM5daFLAARH4tiwbxeGAskRbwly9VofJsXT0
Content-Type: application/json

{
    "notification_active": false
}

###
DELETE http://localhost:3001/v1/delete-notification/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTVlZGU1NGMtZWNmZC00MGE4LWFmYjEtYWIzNjA5OTQ1MjdlIiwibmFtZSI6InJhaG1hdCBhc2lrIiwiZW1haWwiOiJlcmxhbmdnYWhhbmRpa2E3M0BnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc1OTcyMTYzMywiZXhwIjoxNzU5NzIyNTMzfQ.rTAFQcTTLN19CLMfu_-gBDii10a8Y3BprfSEU_ebKq0

